version: "3.9"

services:
  # Speech-to-Text Service
  stt:
    build:
      context: .
      dockerfile: Dockerfile.stt
    container_name: star_wars_stt_service
    ports:
      - "5001:5001"
    environment:
      - PYTHONPATH=/app
      - WHISPER_MODEL=base
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Text-to-Speech Service (Optimized)
  tts:
    build:
      context: .
      dockerfile: Dockerfile.tts
    container_name: star_wars_tts_service
    ports:
      - "5002:5002"
    environment:
      - PYTHONPATH=/app
      - TEMP_DIR=/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # LLM Service
  llm:
    build:
      context: .
      dockerfile: Dockerfile.llm
    container_name: star_wars_llm_service
    ports:
      - "5003:5003"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
      - MODEL_PATH=/app/models/phi-2.Q4_K_M.gguf
      - HF_HOME=/app/models/hf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend Service (Optimized)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: star_wars_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_STT_URL=http://localhost:5001
      - REACT_APP_TTS_URL=http://localhost:5002
      - REACT_APP_LLM_URL=http://localhost:5003
    depends_on:
      stt:
        condition: service_healthy
      tts:
        condition: service_healthy
      llm:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: star_wars_network
    driver: bridge
