services:
  # Speech-to-Text Service
  stt:
    build:
      context: ./stt-service
      dockerfile: Dockerfile
    container_name: star_wars_stt_service
    ports:
      - "5001:5001"
    environment:
      - PYTHONPATH=/app
      - WHISPER_MODEL=base
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Text-to-Speech Service (Optimized)
  tts:
    build:
      context: ./tts-service
      dockerfile: Dockerfile
    container_name: star_wars_tts_service
    ports:
      - "5002:5002"
    environment:
      - PYTHONPATH=/app
      - TEMP_DIR=/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # LLM Service
  llm:
    build:
      context: ./llm-service
      dockerfile: Dockerfile
    container_name: star_wars_llm_service
    ports:
      - "5003:5003"
    environment:
      - PYTHONPATH=/app
      - TEMP_DIR=/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Frontend Service (Optimized)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: star_wars_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_STT_URL=http://star_wars_stt_service:5001
      - REACT_APP_TTS_URL=http://star_wars_tts_service:5002
      - REACT_APP_LLM_URL=http://star_wars_llm_service:5003
    depends_on:
      stt:
        condition: service_healthy
      tts:
        condition: service_healthy
      llm:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: star_wars_network
    driver: bridge
